title: Sigrun
description: > 
  Din beskrivelse her

# Site Author
author:
  name: "Sigrun"
  avatar: "profile.png"  # Du kan legge til et profilbilde senere
  bio: "Din bio"
  location: "Norge"

# Academic websites
googlescholar: "https://scholar.google.com/citations?hl=no&view_op=list_works&gmla=AOv-ny_wrmcIsm5ANL381tyZCje-uNN3A8b3kd1_C5-KxjmyHlfZK0H0lR86fueEyyWoQry9D33NnRxN7O-BWjJ0cxXGbT6IbpX1F1WL&us[...]"
orcid: "https://orcid.org/0000-0002-8570-3201"
cristin: "https://app.cristin.no/persons/show.jsf?id=791793"
linkedin: "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://no.linkedin.com/in/sigrun-lindaas-norhagen-ab97ab96&ved=2ahUKEwjI1fW9mruLAxUwQlUIHWWpHqoQFnoECAwQAQ&usg=[...]"
twitter: "@slindaas"

# Repositories and software development
github: "sigrun"
kaggle: # Username

# Site Settings
locale: "nb-NO"  # Setter norsk som spr√•k
remote_theme: "academicpages/academicpages.github.io"

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Site navigation
include: ["_pages"]
